### ISSUE TITLE
Is there any way to bookmark a note?

### ISSUE THREAD

**Issue by decentropy** [routman/publicnote.com#2]
E..g - can you do publicnote.com/id=mykeyword or something similar?

**Comment by routman** [comment]
Yes, it's possible to do this, but doing so would expose the title and the contents of the note to me, the website owner.  Notes would no longer be private, and it would defeat the purpose of encrypting all notes.  I prefer not to see the plaintext contents of notes stored in my database.

**Comment by decentropy** [comment]
I see..  like web logs & what not.
Understood, thanks!
