### ISSUE TITLE
Server code?

### ISSUE THREAD

**Issue by sirikon** [routman/publicnote.com#4]
It isn’t public?

**Comment by routman** [comment]
There's not much I can share here, as it's built on AWS as a "serverless" web app using various services, such as CloudFront (CDN), API Gateway, AWS WAF (firewall), and DynamoDB.  There are two Lambda functions I wrote to read and write notes from the database, but they are as basic as it gets - I copy/pasted from examples in the tutorials.

**Comment by sirikon** [comment]
For the sake of completion, having those lambdas included with that explanation would be good.

But up to you :)

**Comment by sirikon** [comment]
As a side note: Does that mean that the server does not have any form of validation of the content? Acting as a key/value store that works with any string of text?

**Comment by routman** [comment]
Sure, why not!  I went ahead and added them here.  
[https://github.com/routman/publicnote.com/tree/master/lambda](https://github.com/routman/publicnote.com/tree/master/lambda
)

That's correct, there is no validation or authentication.  There is a size limit in DynamoDB to limit how much can be stored under each note.  There are also rate limiters in place through the firewall to prevent bots or scripts from writing at lot of data at once.  You can even lock yourself out by trying to refresh notes too frequently.

**Comment by sirikon** [comment]
understood :) thanks!!
